# Generated by Django 4.1.4 on 2023-03-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignmentsubmission_assignment_submissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scenario',
        ),
    ]
