# Generated by Django 4.1.4 on 2023-03-10 18:08

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_alter_algscenario_options_algscenariostep'),
        ('assignment', '0005_rename_scenarios_assignment_api_scenarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='alg_scenarios',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='assigments', to='testing.algscenario', verbose_name='Сценарии'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='api_scenarios',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='assigments', to='testing.scenario', verbose_name='Сценарии'),
        ),
    ]
