# Generated by Django 4.1.4 on 2023-03-14 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_assigmentproxy_assigmentsubmissionproxy'),
        ('assignment', '0006_alter_assignment_alg_scenarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classroom.classroom'),
            preserve_default=False,
        ),
    ]
