# Generated by Django 4.1.4 on 2023-03-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_assignment_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(default='В процессе', max_length=25),
        ),
    ]
