# Generated by Django 4.1.4 on 2023-04-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_assignmentsubmission_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticcodeanalysisblock',
            options={'verbose_name': 'Блок Статического анализа', 'verbose_name_plural': 'Блоки Статического анализа'},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='static_analysis_blocks',
        ),
        migrations.AlterField(
            model_name='staticcodeanalysisblock',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='StaticCodeAnalysisPoint',
        ),
    ]
