# Generated by Django 4.1.4 on 2023-04-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_alter_staticcodeanalysisblock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='static_analysis_blocks',
            field=models.ManyToManyField(related_name='assignments', to='assignment.staticcodeanalysisblock'),
        ),
    ]
