# Generated by Django 4.1.4 on 2023-04-03 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_algscenariostep_time'),
        ('assignment', '0010_assignment_static_analysis_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='git_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='static_analysis_blocks',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='assignment.staticcodeanalysisblock', verbose_name='Блоки статического анализа'),
        ),
        migrations.CreateModel(
            name='StaticSubmissionResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.staticcodeanalysisblock')),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignment.assignmentsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='ApiSubmissionResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.step')),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignment.assignmentsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='AlgSubmissionResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.algscenariostep')),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignment.assignmentsubmission')),
            ],
        ),
    ]
