# Generated by Django 4.1.4 on 2023-04-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_assignmentsubmission_git_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='submissions',
        ),
    ]
