# Generated by Django 4.1.4 on 2023-04-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_alter_assignmentsubmission_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
