# Generated by Django 4.1.4 on 2023-04-06 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_algscenariostep_time'),
        ('assignment', '0014_alter_assignmentsubmission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apisubmissionresults',
            name='step',
        ),
        migrations.AddField(
            model_name='algsubmissionresults',
            name='actual',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='algsubmissionresults',
            name='time',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='apisubmissionresults',
            name='body',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='apisubmissionresults',
            name='headers',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='apisubmissionresults',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apisubmissionresults',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apisubmissionresults',
            name='validator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.stepvalidator'),
        ),
    ]
