# Generated by Django 4.1.4 on 2023-04-06 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0015_remove_apisubmissionresults_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisubmissionresults',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='assignment.assignmentsubmission'),
        ),
    ]
