# Generated by Django 4.1.4 on 2023-04-13 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_algscenariostep_name_algscenariostep_points'),
        ('assignment', '0016_alter_apisubmissionresults_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algsubmissionresults',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.algscenariostep', verbose_name='submission_results'),
        ),
        migrations.AlterField(
            model_name='apisubmissionresults',
            name='validator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validated_submissions', to='testing.stepvalidator'),
        ),
    ]
