# Generated by Django 4.1.4 on 2023-05-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0017_alter_algsubmissionresults_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcodeanalysisblock',
            name='code_name',
            field=models.CharField(default='zxc', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
