# Generated by Django 4.1.4 on 2023-05-27 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0018_staticcodeanalysisblock_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticsubmissionresults',
            name='mode',
            field=models.CharField(default='success', max_length=200),
        ),
        migrations.AddField(
            model_name='staticsubmissionresults',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='staticsubmissionresults',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.staticcodeanalysisblock'),
        ),
    ]
