# Generated by Django 4.1.4 on 2023-03-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_scenario_config_alter_step_order_stepvalidator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepvalidator',
            options={},
        ),
        migrations.RemoveField(
            model_name='stepvalidator',
            name='order',
        ),
    ]
