# Generated by Django 4.1.4 on 2023-03-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_stepvalidator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepvalidator',
            name='type',
            field=models.CharField(choices=[('Валидатор статуса', 'expected_status'), ('Сравниватель', 'comparator')], default='Валидатор статуса', max_length=200),
        ),
    ]
