# Generated by Django 4.1.4 on 2023-03-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_stepvalidator_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenario',
            options={'verbose_name': 'Сценарий(Api задание)', 'verbose_name_plural': 'Сценарии(Api задание)'},
        ),
        migrations.AlterModelOptions(
            name='scenarioconfig',
            options={'verbose_name': 'Конфиг Сценария(Api задание)', 'verbose_name_plural': 'Конфииги Сценариев(Api задание)'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order'], 'verbose_name': 'Шаг', 'verbose_name_plural': 'Шаги'},
        ),
        migrations.AlterModelOptions(
            name='stepvalidator',
            options={'verbose_name': 'Валидатор шага', 'verbose_name_plural': 'Валидаторы шага'},
        ),
    ]
