# Generated by Django 4.1.4 on 2023-03-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_alter_scenario_options_alter_scenarioconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название сценария')),
                ('max_points', models.PositiveIntegerField()),
            ],
        ),
    ]
