# Generated by Django 4.1.4 on 2023-04-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_algscenariostep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='algscenariostep',
            name='name',
            field=models.CharField(default='Название', max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='algscenariostep',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
