# Generated by Django 4.1.4 on 2023-03-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout', models.PositiveIntegerField(default=10, verbose_name='Таймаут от зароса')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('max_points', models.PositiveIntegerField()),
                ('config', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario', to='api_test.scenarioconfig', verbose_name='Конфиг')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Номер шага')),
                ('url', models.CharField(max_length=255, verbose_name='Относительный путь')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('HEAD', 'HEAD'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=255, verbose_name='Метод')),
                ('headers', models.JSONField(verbose_name='Заголовки')),
                ('body', models.TextField(verbose_name='Тело Запроса')),
                ('name', models.CharField(help_text='Название шага должно быть уникальным в рамках сценарияд', max_length=255, verbose_name='Название шага')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api_test.scenario', verbose_name='Сценарий')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('scenario', 'name')},
            },
        ),
    ]
