# Generated by Django 4.1.4 on 2023-03-09 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario', to='api_test.scenarioconfig', verbose_name='Конфиг'),
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StepValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=0, help_text='Кол-во баллов за успех')),
                ('actual', models.TextField(blank=True, null=True)),
                ('expected', models.TextField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validators', to='api_test.step')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
