# Generated by Django 4.1.4 on 2023-03-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroom_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='unique_code',
            field=models.CharField(default='0CED5', help_text='Генерируется Автоматически', max_length=255, unique=True, verbose_name='Уникальный код'),
        ),
    ]
