# Generated by Django 4.1.4 on 2023-03-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_delete_scenario'),
        ('classroom', '0009_alter_classroom_unique_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssigmentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assignment.assignment',),
        ),
        migrations.CreateModel(
            name='AssigmentSubmissionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Сдача задания',
                'verbose_name_plural': 'Сдачи заданий',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assignment.assignmentsubmission',),
        ),
    ]
