# Generated by Django 4.1.4 on 2023-03-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='padawanuser',
            managers=[
            ],
        ),
    ]
