# Generated by Django 4.1.4 on 2023-03-10 17:44

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin_interface', '0028_theme_show_fieldsets_as_tabs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='ThemeProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin_interface.theme',),
        ),
    ]
